version: '3.8'
services:
  contact-backend:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    restart: unless-stopped
